"""Configuration defaults for the auto Claude PTY runner."""

from __future__ import annotations


DEFAULT_TIMEOUT_SECONDS = 180 * 60
DEFAULT_IDLE_TIMEOUT_SECONDS = 10 * 60
DEFAULT_MAX_PROMPT_REPEATS = 3
DEFAULT_MIN_REPLY_INTERVAL_SECONDS = 2.0
DEFAULT_NUDGE_AFTER_SECONDS = 30.0
DEFAULT_PROGRESS_INTERVAL_SECONDS = 30.0
DEFAULT_ATTEMPT_INDEX = 0
DEFAULT_CONTEXT_SOFT_LIMIT_TOKENS = 0
DEFAULT_CONTEXT_HARD_LIMIT_TOKENS = 0
DEFAULT_TRANSCRIPT_TAIL_LINES = 120
